### ISSUE TITLE
[Bug]: File Explorer crashes during file renaming

### ISSUE THREAD

**Issue by VortexZero** [frozensnowy/Maelfrost-bugs-suggestions#10]
### Windows version

icebound 

### Importance

Medium

### OS build

1809

### OS Area(s) with issue?

General issue, Performance related issues

### Steps to reproduce

When renaming files back to back in a folder that contains many larg files the entirety of Windows Explorer will crash and restart. I managed to produce this issue while going through some of my data backups on a 2tb sata SSD that did not have the OS installed on it. I was renaming videos in a folder when the entirety of explorer crashed. I was also experiencing slow downs when moving files between folders system wide as in the whole computer would lag, mouse movement and all which should not happen on the hardware I'm running. This would also happen while renaming files.

### ✔️ Expected Behavior

Windows Explorer should not crash or lag the system while manipulating multiple large files.

### ❌ Actual Behavior

Windows Explorer crashes and lags the system when manipulating multiple large files

**Comment by frozensnowy** [comment]
Thanks for the detailed report!

I have a few questions to better understand what goes on here:

What are your system specs + drives you're using to move files between or from?
Are you moving between drives or to the same drive and what drive types are these? (SSD's/HDD's)
Where were the files located originally? On the C drive? Also, windows explorer has issues with paths that are longer than 256 characters.
What is the size of the files you want to move/copy? 
What extension did they have? 
If they have an extension, was/were this/these extension(s) associated with a program?
What third party software was running in the background if any?
Could you open up a task manager on one side and try to manipulate these big files to see if resource usage spikes? Most notably CPU and Disk?


Can you try manipulating these files using command prompt? Do you notice the same slowdowns if you do this? (no need to CD to the location)

You can do this with the following command `move "C:\File\To\Move.extension" "C:\New Path\Without\A\Slash at the end"`
To move multiple files at once, if they have the same extension, use wildcards. EG: `move "C:\All text files\*.txt" "C:\Test"`

Please let me know and again, thanks so much for the report!

**Comment by VortexZero** [comment]
What are your system specs + drives you're using to move files between or from?
System Specs:
- AMD Threadripper 1900X
- Nvidia RTX 2060 (Master) 3 1080p Monitors connected highest hz is 75
- Nvidia GTX 1650 (Slave) Used for encoding and math
- 64 GB DDR4 Max Speed 2400mHz
- C:/ Samsung NvMe m.2 256GB SSD (Icebound Main Install is here)
- D:/ Crucial 2TB Sata SSD (This is what I was moving files around on and renaming nothing moved outside the drive)
- E:/ F:/ G:/ H:/ WD Black 3TB SATA HDD
- I:/ 1TB WD Blue SATA HDD
- K:/ Corsair 128GB NvMe M.2 SSD
- S:/ Samsung NvMe m.2 256GB SSD
- T:/ Samsung NvMe m.2 512GB SSD
- MSI X399 SLI Plus Motherboard
- 750 watt PowerSpec PSU

Are you moving between drives or to the same drive, and what drive types are these? (SSD's/HDD's)
I’m moving files within the same drive

Where were the files located originally? On the C drive? Also, Windows explorer has issues These files with paths that are longer than 256 characters.
File Renames only consisted of a word or 2 all original file names are less than 256 characters. Originally always located on the same drive

What is the size of the files you want to move/copy?
The files I was working with at the time are all less than 8mb, however there are a little over 800 of these files in the folder. I was only working with them one at a time, however.
What extension did they have?
.mp4, .mov, .webm

If they have an extension, was/were this/these extensions(s) associated with a program?
Default program associated with them is VLC media player

What third party software was running in the background, if any?
Discord, Firefox, and Steam

Could you open up a task manager on one side and try to manipulate these big files to see if resource usage spikes? Most notably, CPU and Disk?During the initial performance issues, I did open Task manager and found File explorer using the majority of these resources, which is unusual behavior considering the resources available

Can you try manipulating these files using command prompt? (no need to CD to the location)Tried this and didn’t seem to get any issues

My working theory is File Explorer couldn’t keep up with me renaming then moving files consecutively, ie. Rename the file, move it, repeat.

------- Original Message -------

**Comment by frozensnowy** [comment]
I have been able to reproduce your bug here. I don't think I can supply a fix for it in Icebound, so it'll be fixed for Maelfrost. Also, sorry for the late response and thanks for all the detailed answers!
