### ISSUE TITLE
[Bug]: System failing to pull time from Windows servers

### ISSUE THREAD

**Issue by VortexZero** [frozensnowy/Maelfrost-bugs-suggestions#11]
### Windows version

Icebound

### Importance

Medium

### OS build

Current

### OS Area(s) with issue?

General issue

### Steps to reproduce

Having the computer time pull from time.windows.com will sometimes cause time to be incorrect for the system, sometimes being off by a few minutes, sometimes being wrong entirely. Attempting to turn on "set time automatically" also doesn't work properly at times. I've changed the Internet time pull site to time.nist.gov for the time being which appears to have solved the issue, will continue to monitor. It's entirely possible that my CMOS battery is failing as well, which I will be changing out soon as well.

### ✔️ Expected Behavior

Time should be pulling correctly from MS Servers, could be resolved by changing default to govt time servers

### ❌ Actual Behavior

Time shows incorrectly intermittently when pulled from MS servers.

### Additional Context

This was probably only discovered due to a failing CMOS battery, probably not easily reproducible 

### Workaround or Fix

Change time-server to time.nist.gov

**Comment by frozensnowy** [comment]
Fixed in Maelfrost.
