### ISSUE TITLE
[Request]: Tabs on file explorer

### ISSUE THREAD

**Issue by ghostlyGoldfish** [frozensnowy/Maelfrost-bugs-suggestions#6]
### What new feature would you like to have added to Maelfrost?

A tab for the file explorer, much like in internet browsers, to make working with multiple files easier.
Preferably togglable with the "view" options

### Can this issue be solved with a third-party program?

As far as I know, no.

### Importance

Low

**Comment by frozensnowy** [comment]
Thanks for the request, there is one piece of software that is capable of this, namely [QTTabBar](http://qttabbar.wikidot.com/). I just installed it and it does appear to work correctly in Maelfrost's current branch as seen below:

Would this satisfy your request? 

Could you perhaps install it, try it out and respond here afterwards whether or not this would work?

**Comment by frozensnowy** [comment]
After having discussed this on Discord, QTTabBar seems to be a good solution. Issue closed.
