### ISSUE TITLE
[Request]: YouTube Video Download and Conversion Tool

### ISSUE THREAD

**Issue by VortexZero** [frozensnowy/Maelfrost-bugs-suggestions#7]
### What new feature would you like to have added to Maelfrost?

On the web, there are all kinds of sketchy and frankly trashy YouTube video download tools that don't really have all the features in one tool. Features that would be great to consolidate into a tool like this are as follows:

- Compressionless Download of YouTube videos in any resolution
- Ability to select any desired file format and convert as necessary (ie. mp4 to gif)
- Convert files already on your computer
- Ability to download as just audio at Lossless or lossy
- Hardware decoding/encoding
- Download multiple videos or even playlists at a time
- Download folder selection
- Save playlist downloads as their own folders
- Save videos with or without description and tags in the file
- Download with Thumbnail or download just the thumbnail
- Download with CC (Captions)
- Ability to trim video via time stamps
- Ability to compress video to desired file size (ie. convert to 8mb)
- Perhaps include other sites with video embeds like Twitter, FB, billi billi, ect if not too difficult

### Can this issue be solved with a third-party program?

Yes and No. There's really no one size fits all solution to this issue, and most that try, have various issues and quality of life problems.

### Add any other context, screenshots or mockups for the feature request go here. If you are requesting for third-party software to be integrated into Maelfrost, please link the homepage for it here.

A similar software that attempts and fails these features appears like this 
![image](https://user-images.githubusercontent.com/107147699/172702281-93442f29-70c2-4017-b56b-a4712f295575.png)

(This one is for Bandcamp, but has the same principle behind playlist downloads) 
![image](https://user-images.githubusercontent.com/107147699/172702784-0d20e42c-efd3-49a4-bbe1-85d96accff7e.png)

### Importance

Low

**Comment by VortexZero** [comment]
As discussed on discord, this is just a nice to have and not critical to implement. Conversion tool and video downloader will most likely be separate. This is just an idea for a tool to be created in the future, with the understanding that not everything requested is possible.

**Comment by frozensnowy** [comment]
Issue closing as an alternative has been found by Vortex a while ago.
