### ISSUE TITLE
[Request]: make it not windows 11

### ISSUE THREAD

**Issue by kronuschan** [frozensnowy/Maelfrost-bugs-suggestions#9]
### What new feature would you like to have added to Maelfrost?

from proofofconcepts polls and private message i asked i see it looks same like windows 11 but small changes nothing more but can you add more features that make it is different from it and be its own thing? can you add new ui design more better layout that is different because it looks the same and i think people will think you did not change anything. make it look custom and not windows 11 like can you maybe spend money on artist and programmer idk? maybe other people can give idea on what need to change?

### Add any other context, screenshots or mockups for the feature request go here. If you are requesting for third-party software to be integrated into Maelfrost, please link the homepage for it here.

windows 11 looks the same when compared i think. icebound looks different from windows 7 but why is maelfrost windows 11 the same thing can you explain? 

where did you spend money and time? i dont mean angry but i am asking honest question because you asked open feedback in pm but i wanna know if maybe you can spend less time and do what you like instead of wasting money and time maybe? 

### Importance

High

**Comment by frozensnowy** [comment]
Closed, explained on discord.
